# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'async-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for async-sample
  pod "AsyncSwift"

  target 'async-sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
