# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reveal-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reveal-sample
  pod 'Reveal-SDK', :configurations => ['Debug']
  pod 'SnapKit'

  target 'reveal-sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
