# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'json-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for json-sample
  pod "Unbox"
  pod "Wrap"

  target 'json-sampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
